# Generated by Django 5.0.6 on 2024-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Users',
        ),
    ]
